# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'challenge-pag' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '3.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'UIScrollView-InfiniteScroll'
  pod 'Mantle'
  # Pods for challenge-pag

  target 'challenge-pagTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'

  end

  target 'challenge-pagUITests' do
    # Pods for testing
  end

end
